version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smm
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  api:
    build: ../api
    env_file: ../api/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build: ../frontend
    environment:
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE:-http://localhost:4000}
    depends_on:
      - api

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddydata:/data
    depends_on:
      - frontend
      - api

volumes:
  pgdata: {}
  caddydata: {}
